### ISSUE TITLE
Sorting chests

### ISSUE THREAD

**Issue by thibaultmol** [dthigpen/dtcraft-datapacks#1]
Hi,
I haven't checked yet, but if it could also sort the inventory inside of a chest, that would be great.

(you didn't mention it anywhere, so figured it either hasn't been implemented yet or wasn't written down)

Cheers,

**Comment by dthigpen** [comment]
That's a great idea, it's very easy for chests to get disorganized. I will have to think about how to implement that as there is not a straight forward way to detect when a GUI is opened and what block it's opened at.

It could be implemented by having a chat menu indicate chests in the vicinity of the player, allowing them to click on one to sort.

I'll look into that, thanks

**Comment by dthigpen** [comment]
Over one year later... this feature has been implemented. Closing the issue, but feel free to create a new one if you have additional feature requests or bug fixes
