### ISSUE TITLE
Nether not working

### ISSUE THREAD

**Issue by CrazySaft** [dthigpen/dtcraft-datapacks#5]
Out of any reason the autocrafter does NOT work in nether pls fix this qiuckly bc. i can't use it to craft gold nuggets into ingots from my gold farm

**Comment by dthigpen** [comment]
Thanks for letting me know I'll try to get a fix in the next few days

**Comment by dthigpen** [comment]
Just pushed a fix for this. You can download it from the Releases [here](https://github.com/dthigpen/dtcraft-datapacks/releases/download/v0.0.12/autocraft.zip) or from the Planet Minecraft page.

**Comment by CrazySaft** [comment]
Great thanks

David Thigpen ***@***.***> schrieb am Do., 3. Feb. 2022,
01:06:
